export const getData = async () => {
    return (
        [
            {
                id: "1",
                title: 'Evento Teste 1',
                location: 'Dourados - MS',
                category: 'shows',
                description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut a justo suscipit, bibendum nulla eget, placerat velit. Quisque lacinia varius magna, pellentesque lobortis ex vehicula id. Phasellus ante purus, dignissim vitae augue ut, tristique suscipit ligula. Curabitur vitae suscipit est. Sed ultricies vehicula cursus. Quisque leo orci, viverra non ullamcorper sollicitudin, imperdiet quis nulla. Proin nec neque venenatis lacus congue porttitor. Fusce nibh risus, porttitor vitae enim mattis, cursus tincidunt sem. Integer porta suscipit enim et volutpat. Sed in odio sit amet eros ultricies ultrices vel nec neque. Quisque malesuada, elit nec pharetra laoreet, orci dolor ultricies nibh, eget auctor quam nisi eget nulla. Aenean laoreet velit ac tincidunt fermentum. Fusce sed lectus id nibh cursus viverra at et lorem. In semper eleifend dictum. Morbi volutpat sed ex sed convallis. Integer dignissim est ac massa pellentesque suscipit. Sed elementum velit a elit sollicitudin, in aliquet enim consectetur. Sed ac elit urna. Phasellus sed ante nunc. Vestibulum turpis augue, efficitur eget lorem vitae, feugiat sodales est. Praesent eget elit diam. Nullam ornare eu ex quis auctor. Sed ac quam ut velit placerat viverra eu eget odio. Maecenas mollis scelerisque sem vel congue. Pellentesque id neque nec mauris blandit tincidunt vel in dui. Fusce venenatis, ligula volutpat tincidunt egestas, risus lectus interdum lacus, sodales pulvinar libero odio accumsan purus. Curabitur quis ante id mauris volutpat euismod ut at neque. Nulla aliquam pulvinar nibh nec elementum. Proin venenatis bibendum orci, ac feugiat odio tincidunt sed. Fusce blandit leo odio, eget imperdiet ligula feugiat at. Donec blandit, elit vel tempus pharetra, odio felis tempor enim, ac semper dui turpis at risus.',
                date: '22/11/2022',
                price: 159.90
            },
            {
                id: "2",
                title: 'Evento Teste 2',
                location: 'Dourados - MS',
                category: 'shows',
                description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut a justo suscipit, bibendum nulla eget, placerat velit. Quisque lacinia varius magna, pellentesque lobortis ex vehicula id. Phasellus ante purus, dignissim vitae augue ut, tristique suscipit ligula. Curabitur vitae suscipit est. Sed ultricies vehicula cursus. Quisque leo orci, viverra non ullamcorper sollicitudin, imperdiet quis nulla. Proin nec neque venenatis lacus congue porttitor. Fusce nibh risus, porttitor vitae enim mattis, cursus tincidunt sem. Integer porta suscipit enim et volutpat. Sed in odio sit amet eros ultricies ultrices vel nec neque. Quisque malesuada, elit nec pharetra laoreet, orci dolor ultricies nibh, eget auctor quam nisi eget nulla. Aenean laoreet velit ac tincidunt fermentum. Fusce sed lectus id nibh cursus viverra at et lorem. In semper eleifend dictum. Morbi volutpat sed ex sed convallis. Integer dignissim est ac massa pellentesque suscipit. Sed elementum velit a elit sollicitudin, in aliquet enim consectetur. Sed ac elit urna. Phasellus sed ante nunc. Vestibulum turpis augue, efficitur eget lorem vitae, feugiat sodales est. Praesent eget elit diam. Nullam ornare eu ex quis auctor. Sed ac quam ut velit placerat viverra eu eget odio. Maecenas mollis scelerisque sem vel congue. Pellentesque id neque nec mauris blandit tincidunt vel in dui. Fusce venenatis, ligula volutpat tincidunt egestas, risus lectus interdum lacus, sodales pulvinar libero odio accumsan purus. Curabitur quis ante id mauris volutpat euismod ut at neque. Nulla aliquam pulvinar nibh nec elementum. Proin venenatis bibendum orci, ac feugiat odio tincidunt sed. Fusce blandit leo odio, eget imperdiet ligula feugiat at. Donec blandit, elit vel tempus pharetra, odio felis tempor enim, ac semper dui turpis at risus.',
                date: '22/11/2022',
                price: 159.90
            },
            {
                id: "3",
                title: 'Evento Teste 3',
                location: 'Dourados - MS',
                category: 'shows',
                description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut a justo suscipit, bibendum nulla eget, placerat velit. Quisque lacinia varius magna, pellentesque lobortis ex vehicula id. Phasellus ante purus, dignissim vitae augue ut, tristique suscipit ligula. Curabitur vitae suscipit est. Sed ultricies vehicula cursus. Quisque leo orci, viverra non ullamcorper sollicitudin, imperdiet quis nulla. Proin nec neque venenatis lacus congue porttitor. Fusce nibh risus, porttitor vitae enim mattis, cursus tincidunt sem. Integer porta suscipit enim et volutpat. Sed in odio sit amet eros ultricies ultrices vel nec neque. Quisque malesuada, elit nec pharetra laoreet, orci dolor ultricies nibh, eget auctor quam nisi eget nulla. Aenean laoreet velit ac tincidunt fermentum. Fusce sed lectus id nibh cursus viverra at et lorem. In semper eleifend dictum. Morbi volutpat sed ex sed convallis. Integer dignissim est ac massa pellentesque suscipit. Sed elementum velit a elit sollicitudin, in aliquet enim consectetur. Sed ac elit urna. Phasellus sed ante nunc. Vestibulum turpis augue, efficitur eget lorem vitae, feugiat sodales est. Praesent eget elit diam. Nullam ornare eu ex quis auctor. Sed ac quam ut velit placerat viverra eu eget odio. Maecenas mollis scelerisque sem vel congue. Pellentesque id neque nec mauris blandit tincidunt vel in dui. Fusce venenatis, ligula volutpat tincidunt egestas, risus lectus interdum lacus, sodales pulvinar libero odio accumsan purus. Curabitur quis ante id mauris volutpat euismod ut at neque. Nulla aliquam pulvinar nibh nec elementum. Proin venenatis bibendum orci, ac feugiat odio tincidunt sed. Fusce blandit leo odio, eget imperdiet ligula feugiat at. Donec blandit, elit vel tempus pharetra, odio felis tempor enim, ac semper dui turpis at risus.',
                date: '22/11/2022',
                price: 159.90
            },
            {
                id: "4",
                title: 'Evento Teste 4',
                location: 'Dourados - MS',
                category: 'shows',
                description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut a justo suscipit, bibendum nulla eget, placerat velit. Quisque lacinia varius magna, pellentesque lobortis ex vehicula id. Phasellus ante purus, dignissim vitae augue ut, tristique suscipit ligula. Curabitur vitae suscipit est. Sed ultricies vehicula cursus. Quisque leo orci, viverra non ullamcorper sollicitudin, imperdiet quis nulla. Proin nec neque venenatis lacus congue porttitor. Fusce nibh risus, porttitor vitae enim mattis, cursus tincidunt sem. \nInteger porta suscipit enim et volutpat. Sed in odio sit amet eros ultricies ultrices vel nec neque. Quisque malesuada, elit nec pharetra laoreet, orci dolor ultricies nibh, eget auctor quam nisi eget nulla. Aenean laoreet velit ac tincidunt fermentum. Fusce sed lectus id nibh cursus viverra at et lorem. In semper eleifend dictum. Morbi volutpat sed ex sed convallis. Integer dignissim est ac massa pellentesque suscipit. Sed elementum velit a elit sollicitudin, in aliquet enim consectetur. Sed ac elit urna. Phasellus sed ante nunc. Vestibulum turpis augue, efficitur eget lorem vitae, feugiat sodales est. Praesent eget elit diam. Nullam ornare eu ex quis auctor. Sed ac quam ut velit placerat viverra eu eget odio. Maecenas mollis scelerisque sem vel congue. Pellentesque id neque nec mauris blandit tincidunt vel in dui. Fusce venenatis, ligula volutpat tincidunt egestas, risus lectus interdum lacus, sodales pulvinar libero odio accumsan purus. Curabitur quis ante id mauris volutpat euismod ut at neque. Nulla aliquam pulvinar nibh nec elementum. Proin venenatis bibendum orci, ac feugiat odio tincidunt sed. Fusce blandit leo odio, eget imperdiet ligula feugiat at. Donec blandit, elit vel tempus pharetra, odio felis tempor enim, ac semper dui turpis at risus.',
                date: '22/11/2022',
                price: 159.90
            },
            {
                id: "5",
                title: 'Evento Teste 5',
                location: 'Dourados - MS',
                category: 'shows',
                description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut a justo suscipit, bibendum nulla eget, placerat velit. Quisque lacinia varius magna, pellentesque lobortis ex vehicula id. Phasellus ante purus, dignissim vitae augue ut, tristique suscipit ligula. Curabitur vitae suscipit est. Sed ultricies vehicula cursus. Quisque leo orci, viverra non ullamcorper sollicitudin, imperdiet quis nulla. Proin nec neque venenatis lacus congue porttitor. Fusce nibh risus, porttitor vitae enim mattis, cursus tincidunt sem. Integer porta suscipit enim et volutpat. Sed in odio sit amet eros ultricies ultrices vel nec neque. Quisque malesuada, elit nec pharetra laoreet, orci dolor ultricies nibh, eget auctor quam nisi eget nulla. Aenean laoreet velit ac tincidunt fermentum. Fusce sed lectus id nibh cursus viverra at et lorem. In semper eleifend dictum. Morbi volutpat sed ex sed convallis. Integer dignissim est ac massa pellentesque suscipit. Sed elementum velit a elit sollicitudin, in aliquet enim consectetur. Sed ac elit urna. Phasellus sed ante nunc. Vestibulum turpis augue, efficitur eget lorem vitae, feugiat sodales est. Praesent eget elit diam. Nullam ornare eu ex quis auctor. Sed ac quam ut velit placerat viverra eu eget odio. Maecenas mollis scelerisque sem vel congue. Pellentesque id neque nec mauris blandit tincidunt vel in dui. Fusce venenatis, ligula volutpat tincidunt egestas, risus lectus interdum lacus, sodales pulvinar libero odio accumsan purus. Curabitur quis ante id mauris volutpat euismod ut at neque. Nulla aliquam pulvinar nibh nec elementum. Proin venenatis bibendum orci, ac feugiat odio tincidunt sed. Fusce blandit leo odio, eget imperdiet ligula feugiat at. Donec blandit, elit vel tempus pharetra, odio felis tempor enim, ac semper dui turpis at risus.',
                date: '22/11/2022',
                price: 159.90
            },
        ]
    )
}
